name: Generate Doxygen documentation

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v3.5.2

    - name: Configure docs dir
      run: mkdir docs

    - name: Generate documentation
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: "."

    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
